pre-push hookでエラーが出る問題を修正など

diff --git a/.git_template/hooks/pre-push b/.git_template/hooks/pre-push
--- a/.git_template/hooks/pre-push
+++ b/.git_template/hooks/pre-push
@@ -22,36 +22,37 @@
 remote="$1"
 url="$2"
 
-re=`git config pre-push.grep`
+re=$(git config pre-push.grep)
 [ -z "$re" ] && exit 0
-maxcount=`git config pre-push.max-count`
+maxcount=$(git config pre-push.max-count)
 [ -z "$maxcount" ] && maxcount=10
 
 z40=0000000000000000000000000000000000000000
 
 while read local_ref local_sha remote_ref remote_sha
 do
-    if [ "$local_sha" = $z40 ]
+  if [ "$local_sha" = $z40 ]
+  then
+    # Handle delete
+    :
+  else
+    if [ "$remote_sha" = $z40 ]
     then
-        # Handle delete
-        :
+      # New branch, examine all commits
+      range=$(git rev-list --max-count=$maxcount $local_sha)
     else
-        if [ "$remote_sha" = $z40 ]
-        then
-            # New branch, examine all commits
-            range=`git rev-list --max-count=$maxcount $local_sha`
-        else
-            # Update to existing branch, examine new commits
-            range="$remote_sha..$local_sha"
-        fi
-
-        # Check for commit that can't pushed
-        commit=`git rev-list -n 1 --grep "$re" "$range"`
-        if [ -n "$commit" ]
-        then
-            echo >&2 "Found commit that can't push in $local_ref, not pushing"
-            exit 1
-        fi
+      # Update to existing branch, examine new commits
+      range="$remote_sha..$local_sha"
     fi
+    range=$(echo "$range" | tr '\n' ' ')
+
+    # Check for commit that can't pushed
+    commit=$(git rev-list -n 1 --grep "$re" $range)
+    if [ -n "$commit" ]
+    then
+      echo >&2 "Found commit that can't push in $local_ref, not pushing(by pre-push hook)"
+      exit 1
+    fi
+  fi
 done
 
